import json
import os
import sys
import time
import re
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from PySide6.QtCore import QObject, QThread, Signal, QTimer, Qt
from PySide6.QtGui import QTextCursor, QIcon, QPixmap, QFont
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QComboBox,
    QProgressBar,
    QTabWidget,
    QVBoxLayout,
    QWidget,
    QFormLayout,
    QGroupBox,
    QSpinBox,
    QSplitter,
    QDialog,
    QRadioButton,
    QButtonGroup,
    QCheckBox,
    QScrollArea,
)

from pipeline import generate, estimate_topic_scope
from research import normalize_urls
from llm import (
    LlamaServer,
    LlamaServerProcess,
    find_llama_server_exe,
    find_default_gguf_model,
    get_app_dir,
    get_bundle_dir,
)

load_dotenv()

CONFIG_FILE_NAME = "config.json"


def get_icon_path():
    for base in [get_bundle_dir(), get_app_dir(), Path(".")]:
        for name in ["icon.png", "icon.ico"]:
            p = base / name
            if p.exists():
                return str(p.resolve())
    return ""


def load_config():
    config_path = get_app_dir() / CONFIG_FILE_NAME
    if config_path.exists():
        try:
            return json.loads(config_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_config(data):
    try:
        config_path = get_app_dir() / CONFIG_FILE_NAME
        config_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception:
        pass


def write_docx_file(filepath: Path, title: str, content: str, topic: str, duration_info: str):
    """Write cleanly formatted Microsoft Word document (.docx)."""
    try:
        import docx
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = docx.Document()
        for section in doc.sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)

        # Title
        h1 = doc.add_heading(title, level=1)
        h1.alignment = WD_ALIGN_PARAGRAPH.LEFT

        # Meta
        p_meta = doc.add_paragraph()
        r_meta = p_meta.add_run(f"Topic: {topic}\nTarget Length: {duration_info}\nGenerated by ScriptMaker on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
        r_meta.italic = True
        r_meta.font.color.rgb = RGBColor(100, 100, 100)

        doc.add_paragraph("―" * 45)

        for block in content.split("\n\n"):
            block = block.strip()
            if not block:
                continue
            if block.startswith("# "):
                doc.add_heading(block.lstrip("# ").strip(), level=1)
            elif block.startswith("## "):
                doc.add_heading(block.lstrip("# ").strip(), level=2)
            elif block.startswith("### "):
                doc.add_heading(block.lstrip("# ").strip(), level=3)
            elif block.startswith("**[") and "]" in block:
                p = doc.add_paragraph()
                r = p.add_run(block)
                r.bold = True
            elif block.startswith("[B-ROLL:") or block.startswith("[VISUAL:"):
                p = doc.add_paragraph()
                r = p.add_run(block)
                r.italic = True
                r.font.color.rgb = RGBColor(0, 102, 204)
            else:
                doc.add_paragraph(block)

        doc.save(str(filepath))
        return True
    except Exception as exc:
        raise RuntimeError(f"Error writing DOCX file: {exc}")


class GenerateOptionsDialog(QDialog):
    """Pre-generation options dialog to choose which components to generate."""
    def __init__(self, parent, target_mins: int, target_words: int):
        super().__init__(parent)
        self.setWindowTitle("Generation Options & Checklist")
        self.resize(460, 310)

        layout = QVBoxLayout(self)

        info_lbl = QLabel(f"<b>Target Scope:</b> {target_mins} mins (~{target_words} words)")
        layout.addWidget(info_lbl)

        group = QGroupBox("Select What to Generate:")
        grp_layout = QVBoxLayout(group)

        self.chk_brief = QCheckBox("🌐 Web/YouTube Research & Structured Brief")
        self.chk_brief.setChecked(True)
        grp_layout.addWidget(self.chk_brief)

        self.chk_yt = QCheckBox("🎬 Version B — High-Retention YouTube Script")
        self.chk_yt.setChecked(True)
        grp_layout.addWidget(self.chk_yt)

        self.chk_doc = QCheckBox("📽️ Version A — Documentary Script")
        self.chk_doc.setChecked(True)
        grp_layout.addWidget(self.chk_doc)

        self.chk_scope_alert = QCheckBox("🔍 Check topic scope & alert if research has many subtopics")
        self.chk_scope_alert.setChecked(True)
        grp_layout.addWidget(self.chk_scope_alert)

        layout.addWidget(group)

        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        cancel_btn = QPushButton("Cancel")
        cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(cancel_btn)

        self.start_btn = QPushButton("🚀 Start Generation")
        self.start_btn.setStyleSheet("font-weight: bold; background-color: #1976d2; color: white; padding: 6px 16px;")
        self.start_btn.clicked.connect(self.accept)
        btn_layout.addWidget(self.start_btn)
        layout.addLayout(btn_layout)


class ScopeEstimateDialog(QDialog):
    """Dialog alerting the user when research contains many items exceeding the target length."""
    def __init__(self, parent, topic: str, item_count: int, cur_words: int, cur_mins: int, rec_words: int, rec_mins: int):
        super().__init__(parent)
        self.setWindowTitle("Topic Scope & Length Optimization")
        self.resize(520, 360)

        self.rec_words = rec_words
        self.rec_mins = rec_mins
        self.cur_words = cur_words
        self.cur_mins = cur_mins

        self.final_words = cur_words
        self.final_mins = cur_mins

        layout = QVBoxLayout(self)

        header = QLabel("<h3>🔍 Dense Topic Detected!</h3>")
        layout.addWidget(header)

        desc = QLabel(
            f"The research material contains <b>{item_count} distinct announcements/topics</b>.<br><br>"
            f"• <b>Current Target:</b> {cur_mins} mins (~{cur_words} words) &rarr; <i>~{int(cur_words/item_count)} words/item (very compressed)</i><br>"
            f"• <b>Recommended:</b> <b>{rec_mins} mins (~{rec_words} words)</b> &rarr; <i>~85 words/item for full coverage</i>"
        )
        desc.setWordWrap(True)
        layout.addWidget(desc)

        group = QGroupBox("Choose Writing Target:")
        grp_layout = QVBoxLayout(group)

        self.rad_rec = QRadioButton(f"✨ Auto-Adjust to Recommended: {rec_mins} mins (~{rec_words} words)")
        self.rad_rec.setChecked(True)
        grp_layout.addWidget(self.rad_rec)

        self.rad_cur = QRadioButton(f"⚡ Keep Current Target: {cur_mins} mins (~{cur_words} words) [Ultra-concise summary]")
        grp_layout.addWidget(self.rad_cur)

        self.rad_custom = QRadioButton("⚙️ Specify Custom Duration:")
        grp_layout.addWidget(self.rad_custom)

        custom_row = QHBoxLayout()
        self.spin_mins = QSpinBox()
        self.spin_mins.setRange(1, 60)
        self.spin_mins.setValue(rec_mins)
        self.spin_mins.setSuffix(" mins")
        self.spin_mins.setEnabled(False)
        self.lbl_custom_words = QLabel(f"(~{rec_words} words)")
        self.spin_mins.valueChanged.connect(self.on_spin_changed)
        custom_row.addWidget(self.spin_mins)
        custom_row.addWidget(self.lbl_custom_words)
        custom_row.addStretch()
        grp_layout.addLayout(custom_row)

        self.rad_custom.toggled.connect(self.spin_mins.setEnabled)
        layout.addWidget(group)

        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        cancel_btn = QPushButton("Cancel")
        cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(cancel_btn)

        proceed_btn = QPushButton("Proceed with Writing")
        proceed_btn.setStyleSheet("font-weight: bold; background-color: #2e7d32; color: white; padding: 6px 16px;")
        proceed_btn.clicked.connect(self.on_proceed)
        btn_layout.addWidget(proceed_btn)
        layout.addLayout(btn_layout)

    def on_spin_changed(self):
        m = self.spin_mins.value()
        w = m * 200
        self.lbl_custom_words.setText(f"(~{w} words)")

    def on_proceed(self):
        if self.rad_rec.isChecked():
            self.final_words = self.rec_words
            self.final_mins = self.rec_mins
        elif self.rad_cur.isChecked():
            self.final_words = self.cur_words
            self.final_mins = self.cur_mins
        else:
            self.final_mins = self.spin_mins.value()
            self.final_words = self.final_mins * 200
        self.accept()


class ExportDialog(QDialog):
    def __init__(self, parent, default_topic: str, result_data: dict, duration_str: str):
        super().__init__(parent)
        self.setWindowTitle("Export Scripts & Research")
        self.resize(520, 380)
        self.result_data = result_data
        self.duration_str = duration_str

        raw_topic = default_topic or "script"
        self.safe_topic = re.sub(r'[\\/*?:"<>|]', '_', raw_topic)
        self.safe_topic = re.sub(r'\s+', ' ', self.safe_topic).strip()[:70] or "script"

        layout = QVBoxLayout(self)

        fmt_group = QGroupBox("Select Export Format:")
        fmt_layout = QVBoxLayout(fmt_group)

        self.radio_docx = QRadioButton("Microsoft Word Document (.docx) — Recommended for writers")
        self.radio_txt = QRadioButton("Plain Text File (.txt) — Universal readable text")
        self.radio_md = QRadioButton("Markdown File (.md) — Formatted with headers and bullets")
        self.radio_all = QRadioButton("All Formats (.docx + .txt + .md)")
        self.radio_docx.setChecked(True)

        fmt_layout.addWidget(self.radio_docx)
        fmt_layout.addWidget(self.radio_txt)
        fmt_layout.addWidget(self.radio_md)
        fmt_layout.addWidget(self.radio_all)
        layout.addWidget(fmt_group)

        items_group = QGroupBox("Files to Include:")
        items_layout = QVBoxLayout(items_group)
        self.chk_doc = QCheckBox("Version A — Documentary Script")
        self.chk_yt = QCheckBox("Version B — High-Retention YouTube Script")
        self.chk_json = QCheckBox("Full Research Brief & Evidence (JSON)")
        self.chk_doc.setChecked(True)
        self.chk_yt.setChecked(True)
        self.chk_json.setChecked(True)
        items_layout.addWidget(self.chk_doc)
        items_layout.addWidget(self.chk_yt)
        items_layout.addWidget(self.chk_json)
        layout.addWidget(items_group)

        fld_layout = QHBoxLayout()
        fld_layout.addWidget(QLabel("Output Folder:"))
        self.folder_input = QLineEdit(str(Path.home() / "Documents"))
        fld_layout.addWidget(self.folder_input)
        browse_fld_btn = QPushButton("Browse...")
        browse_fld_btn.clicked.connect(self.browse_folder)
        fld_layout.addWidget(browse_fld_btn)
        layout.addLayout(fld_layout)

        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        cancel_btn = QPushButton("Cancel")
        cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(cancel_btn)

        self.export_btn = QPushButton("Export Now")
        self.export_btn.setStyleSheet("font-weight: bold; background-color: #1976d2; color: white; padding: 6px 16px;")
        self.export_btn.clicked.connect(self.do_export)
        btn_layout.addWidget(self.export_btn)
        layout.addLayout(btn_layout)

        self.exported_folder = None
        self.exported_files = []

    def browse_folder(self):
        f = QFileDialog.getExistingDirectory(self, "Select Output Directory", self.folder_input.text())
        if f:
            self.folder_input.setText(f)

    def do_export(self):
        folder = Path(self.folder_input.text().strip())
        if not folder.exists() or not folder.is_dir():
            QMessageBox.warning(self, "Invalid Folder", "Please select a valid folder.")
            return

        is_docx = self.radio_docx.isChecked() or self.radio_all.isChecked()
        is_txt = self.radio_txt.isChecked() or self.radio_all.isChecked()
        is_md = self.radio_md.isChecked() or self.radio_all.isChecked()

        exported = []
        topic_name = self.safe_topic

        script_a = self.result_data.get("script_a", "")
        script_b = self.result_data.get("script_b", "")
        brief_data = self.result_data.get("brief", {})

        try:
            if self.chk_doc.isChecked() and script_a:
                if is_docx:
                    p = folder / f"{topic_name}_documentary.docx"
                    write_docx_file(p, f"{topic_name} — Documentary Script", script_a, topic_name, self.duration_str)
                    exported.append(p.name)
                if is_txt:
                    p = folder / f"{topic_name}_documentary.txt"
                    p.write_text(f"TOPIC: {topic_name}\nFORMAT: Documentary Script\nTARGET: {self.duration_str}\n\n{script_a}", encoding="utf-8")
                    exported.append(p.name)
                if is_md:
                    p = folder / f"{topic_name}_documentary.md"
                    p.write_text(f"# {topic_name} — Documentary Script\n\n> Target: {self.duration_str}\n\n{script_a}", encoding="utf-8")
                    exported.append(p.name)

            if self.chk_yt.isChecked() and script_b:
                if is_docx:
                    p = folder / f"{topic_name}_youtube.docx"
                    write_docx_file(p, f"{topic_name} — High-Retention YouTube Script", script_b, topic_name, self.duration_str)
                    exported.append(p.name)
                if is_txt:
                    p = folder / f"{topic_name}_youtube.txt"
                    p.write_text(f"TOPIC: {topic_name}\nFORMAT: YouTube Script\nTARGET: {self.duration_str}\n\n{script_b}", encoding="utf-8")
                    exported.append(p.name)
                if is_md:
                    p = folder / f"{topic_name}_youtube.md"
                    p.write_text(f"# {topic_name} — YouTube Script\n\n> Target: {self.duration_str}\n\n{script_b}", encoding="utf-8")
                    exported.append(p.name)

            if self.chk_json.isChecked() and brief_data:
                p = folder / f"{topic_name}_research.json"
                p.write_text(json.dumps(brief_data, indent=2, ensure_ascii=False), encoding="utf-8")
                exported.append(p.name)

            self.exported_folder = folder
            self.exported_files = exported
            self.accept()

        except Exception as exc:
            QMessageBox.critical(self, "Export Error", f"Failed to export scripts:\n{exc}")


class ChatWorker(QThread):
    stream_token = Signal(str)
    finished_ok = Signal(str)
    failed = Signal(str)

    def __init__(self, llama_url: str, messages: list):
        super().__init__()
        self.llama_url = llama_url
        self.messages = messages

    def run(self):
        try:
            llama = LlamaServer(self.llama_url)
            full_response = llama.chat_conversation_stream(
                messages=self.messages,
                temperature=0.5,
                max_tokens=4000,
                on_token=self.stream_token.emit,
            )
            self.finished_ok.emit(full_response)
        except Exception as exc:
            self.failed.emit(str(exc))


class AIChatDialog(QDialog):
    """Interactive AI Assistant window for revising, refining, and conversing about the script."""
    def __init__(self, parent, llama_url: str, topic: str, active_tab_title: str, active_text: str, brief_data: dict, apply_callback=None):
        super().__init__(parent)
        self.setWindowTitle(f"💬 AI Script Assistant — {active_tab_title}")
        self.resize(750, 620)
        self.llama_url = llama_url
        self.active_tab_title = active_tab_title
        self.apply_callback = apply_callback
        self.chat_worker = None

        self.messages = []
        system_context = (
            f"You are ScriptMaker's AI Scriptwriting Assistant.\n"
            f"TOPIC: {topic}\n"
            f"ACTIVE WORKING DRAFT ({active_tab_title}):\n{active_text[:6000]}\n\n"
            f"INSTRUCTION: Help the user refine, expand, condense, polish, or modify this script as requested. "
            f"Keep facts grounded in the topic. Write clearly for spoken video narration."
        )
        self.messages.append({"role": "system", "content": system_context})

        layout = QVBoxLayout(self)

        # Quick Action Chips
        chips_layout = QHBoxLayout()
        chips_layout.addWidget(QLabel("<b>Quick Actions:</b>"))
        actions = [
            ("⚡ Hook Polish", "Rewrite the opening Hook to be significantly punchier and higher-retention."),
            ("🎥 Add Visual Cues", "Add descriptive [B-ROLL: ...] visual and editing cues throughout the script."),
            ("✂️ Condense Script", "Condense this script while retaining all key announcements/points."),
            ("🔥 Punchier Tone", "Make the narrative voice faster-paced and more engaging for YouTube."),
        ]
        for label, prompt in actions:
            btn = QPushButton(label)
            btn.setStyleSheet("padding: 3px 8px; font-size: 11px;")
            btn.clicked.connect(lambda _, p=prompt: self.send_prompt(p))
            chips_layout.addWidget(btn)
        chips_layout.addStretch()
        layout.addLayout(chips_layout)

        # Chat History View
        self.chat_history = QPlainTextEdit()
        self.chat_history.setReadOnly(True)
        self.chat_history.setStyleSheet(
            "QPlainTextEdit { background-color: #1e1e1e; color: #f0f0f0; font-size: 13px; font-family: 'Segoe UI', sans-serif; line-height: 1.4; border-radius: 6px; padding: 8px; }"
        )
        layout.addWidget(self.chat_history)

        self.append_system_msg(f"👋 Script Assistant ready for <b>{active_tab_title}</b>. Ask for edits, rewrites, or section enhancements!")

        # User Input Box
        input_layout = QHBoxLayout()
        self.input_field = QPlainTextEdit()
        self.input_field.setPlaceholderText("Type your instruction (e.g., 'Make section 2 more detailed with Marvel facts')...")
        self.input_field.setMaximumHeight(70)
        self.input_field.setStyleSheet("font-size: 13px;")
        input_layout.addWidget(self.input_field)

        self.send_btn = QPushButton("Send ↵")
        self.send_btn.setStyleSheet("font-weight: bold; background-color: #1976d2; color: white; padding: 12px 18px;")
        self.send_btn.clicked.connect(self.send_user_message)
        input_layout.addWidget(self.send_btn)
        layout.addLayout(input_layout)

        # Bottom Controls
        bottom_layout = QHBoxLayout()
        clear_btn = QPushButton("Clear Chat")
        clear_btn.clicked.connect(self.clear_chat)
        bottom_layout.addWidget(clear_btn)

        bottom_layout.addStretch()

        self.copy_btn = QPushButton("📋 Copy Last Response")
        self.copy_btn.clicked.connect(self.copy_last_response)
        bottom_layout.addWidget(self.copy_btn)

        self.apply_btn = QPushButton("✨ Apply / Replace in Active Tab")
        self.apply_btn.setStyleSheet("font-weight: bold; background-color: #2e7d32; color: white; padding: 6px 14px;")
        self.apply_btn.clicked.connect(self.apply_to_tab)
        bottom_layout.addWidget(self.apply_btn)

        layout.addLayout(bottom_layout)

        self.last_assistant_response = ""

    def append_system_msg(self, text: str):
        self.chat_history.appendHtml(f"<div style='color: #888; margin-bottom: 8px;'><i>{text}</i></div>")

    def append_user_msg(self, text: str):
        self.chat_history.appendHtml(f"<div style='color: #64b5f6; font-weight: bold; margin-top: 10px;'>👤 You:</div><div style='margin-bottom: 10px; color: #fff;'>{text}</div>")

    def send_prompt(self, prompt: str):
        self.input_field.setPlainText(prompt)
        self.send_user_message()

    def send_user_message(self):
        text = self.input_field.toPlainText().strip()
        if not text:
            return

        self.input_field.clear()
        self.append_user_msg(text)
        self.messages.append({"role": "user", "content": text})

        self.chat_history.appendHtml(f"<div style='color: #81c784; font-weight: bold; margin-top: 8px;'>🤖 AI Assistant:</div>")
        self.send_btn.setEnabled(False)
        self.last_assistant_response = ""

        self.chat_worker = ChatWorker(self.llama_url, self.messages)
        self.chat_worker.stream_token.connect(self.on_chat_token)
        self.chat_worker.finished_ok.connect(self.on_chat_done)
        self.chat_worker.failed.connect(self.on_chat_error)
        self.chat_worker.start()

    def on_chat_token(self, token: str):
        self.last_assistant_response += token
        self.chat_history.moveCursor(QTextCursor.End)
        self.chat_history.insertPlainText(token)
        self.chat_history.ensureCursorVisible()

    def on_chat_done(self, full_text: str):
        self.last_assistant_response = full_text
        self.messages.append({"role": "assistant", "content": full_text})
        self.chat_history.appendPlainText("\n")
        self.send_btn.setEnabled(True)

    def on_chat_error(self, err: str):
        self.chat_history.appendHtml(f"<div style='color: #e57373;'><b>Error:</b> {err}</div>")
        self.send_btn.setEnabled(True)

    def copy_last_response(self):
        if self.last_assistant_response:
            QApplication.clipboard().setText(self.last_assistant_response)
            QMessageBox.information(self, "Copied", "AI response copied to clipboard!")

    def apply_to_tab(self):
        if not self.last_assistant_response:
            QMessageBox.warning(self, "Nothing to apply", "Generate a response first.")
            return
        if self.apply_callback:
            self.apply_callback(self.last_assistant_response)
            QMessageBox.information(self, "Applied", f"Response applied to '{self.active_tab_title}' tab!")

    def clear_chat(self):
        self.chat_history.clear()
        self.messages = [self.messages[0]]
        self.append_system_msg("Chat reset. Ready for new instructions.")


class ServerLogBridge(QObject):
    log_message = Signal(str)


class ServerWaitThread(QThread):
    progress = Signal(str)
    ready = Signal(bool)

    def __init__(self, llama_url: str, timeout_sec: int = 90):
        super().__init__()
        self.llama_url = llama_url
        self.timeout_sec = timeout_sec

    def run(self):
        llama = LlamaServer(self.llama_url)
        start = time.time()
        while time.time() - start < self.timeout_sec:
            if llama.health(timeout=1.5):
                self.ready.emit(True)
                return
            elapsed = int(time.time() - start)
            self.progress.emit(f"Waiting for local server readiness ({elapsed}s)...")
            time.sleep(1.5)
        self.ready.emit(False)


class Worker(QThread):
    progress = Signal(str)
    stream_token = Signal(str, str)
    finished_ok = Signal(dict)
    failed = Signal(str)

    def __init__(self, urls, topic, mode, tavily_key, llama_url, llama_exe, gguf_model, ngl, context, target_words, target_minutes, do_brief, do_youtube, do_doc, check_scope, server_proc_ref, log_callback=None):
        super().__init__()
        self.urls = urls
        self.topic = topic
        self.mode = mode
        self.tavily_key = tavily_key
        self.llama_url = llama_url
        self.llama_exe = llama_exe
        self.gguf_model = gguf_model
        self.ngl = ngl
        self.context = context
        self.target_words = target_words
        self.target_minutes = target_minutes
        self.do_brief = do_brief
        self.do_youtube = do_youtube
        self.do_doc = do_doc
        self.check_scope = check_scope
        self.server_proc_ref = server_proc_ref
        self.log_callback = log_callback

    def run(self):
        try:
            llama = LlamaServer(self.llama_url)
            if not llama.health(timeout=1.5):
                if not self.gguf_model or not os.path.isfile(self.gguf_model):
                    raise RuntimeError(
                        f"llama-server is not running at {self.llama_url} and no valid GGUF model file was selected.\n\n"
                        "Please click 'Browse GGUF...' to select your model file."
                    )
                if not self.llama_exe or not os.path.isfile(self.llama_exe):
                    raise RuntimeError(
                        f"llama-server executable not found at: '{self.llama_exe}'.\n\n"
                        "Please click 'Browse EXE...' to select llama-server.exe."
                    )

                self.progress.emit("Launching local llama-server with GGUF model...")
                if self.log_callback:
                    self.log_callback(f"[ScriptMaker] Auto-starting llama-server on {self.llama_url}...")
                    self.log_callback(f"[ScriptMaker] Model: {self.gguf_model}")

                proc = LlamaServerProcess(
                    exe_path=self.llama_exe,
                    model_path=self.gguf_model,
                    port=8080,
                    ngl=self.ngl,
                    context=self.context,
                    parallel=1,
                    flash_attention=True,
                    log_callback=self.log_callback,
                )
                proc.start()
                self.server_proc_ref[0] = proc

                ready = llama.wait_until_ready(timeout_sec=90, progress_cb=self.progress.emit)
                if not ready:
                    raise RuntimeError(
                        "llama-server process started but failed to become ready within 90 seconds.\n"
                        "Check the console logs for details."
                    )
                if self.log_callback:
                    self.log_callback("[ScriptMaker] Server is ready! Starting research...")

            result = generate(
                self.urls,
                self.topic,
                self.mode,
                self.tavily_key,
                self.llama_url,
                progress=self.progress.emit,
                on_stream=self.stream_token.emit,
                target_words=self.target_words,
                target_minutes=self.target_minutes,
                do_brief=self.do_brief,
                do_youtube=self.do_youtube,
                do_documentary=self.do_doc,
            )
            self.finished_ok.emit(result)
        except Exception as exc:
            self.failed.emit(str(exc))


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("ScriptMaker — Local AI & YouTube Script Studio")
        self.resize(1380, 920)

        self.icon_path = get_icon_path()
        if self.icon_path:
            self.setWindowIcon(QIcon(self.icon_path))

        self.result = None
        self.worker = None
        self.wait_thread = None
        self.server_proc_ref = [None]

        # Smooth token streaming buffer
        self.token_buffer = {"brief": [], "script_a": [], "script_b": []}
        self.stream_timer = QTimer(self)
        self.stream_timer.setInterval(35)
        self.stream_timer.timeout.connect(self.flush_stream_buffer)
        self.stream_timer.start()

        self.log_bridge = ServerLogBridge()
        self.log_bridge.log_message.connect(self.append_log)

        self.config = load_config()

        # Dual-Pane Splitter (Left: Controls & Console Logs, Right: Live Script Tabs)
        self.splitter = QSplitter(Qt.Horizontal)

        # ----------------------------------------------------
        # LEFT PANE: Setup, Configuration & Real-Time Console Logs
        # ----------------------------------------------------
        left_widget = QWidget()
        left_layout = QVBoxLayout(left_widget)
        left_layout.setContentsMargins(10, 10, 10, 10)

        # Header with App Logo
        header_layout = QHBoxLayout()
        if self.icon_path:
            logo_lbl = QLabel()
            pix = QPixmap(self.icon_path).scaled(46, 46, Qt.KeepAspectRatio, Qt.SmoothTransformation)
            logo_lbl.setPixmap(pix)
            header_layout.addWidget(logo_lbl)

        title_vbox = QVBoxLayout()
        title_vbox.setSpacing(2)
        title = QLabel("<h2 style='margin:0; padding:0;'>ScriptMaker Studio</h2>")
        title_vbox.addWidget(title)
        title_vbox.addWidget(
            QLabel("Autonomous Multi-Source Research & Grounded Local Script Generation")
        )
        header_layout.addLayout(title_vbox)
        header_layout.addStretch()
        left_layout.addLayout(header_layout)

        # Model & Server Settings Group
        model_group = QGroupBox("Local GGUF Model & llama-server Settings")
        model_layout = QVBoxLayout(model_group)

        # GGUF Model Path
        gguf_layout = QHBoxLayout()
        gguf_layout.addWidget(QLabel("Model:"))
        saved_gguf = self.config.get("gguf_model_path", "")
        default_gguf = saved_gguf if (saved_gguf and os.path.exists(saved_gguf)) else find_default_gguf_model()
        self.gguf_path_input = QLineEdit(default_gguf)
        self.gguf_path_input.setPlaceholderText("Select a .gguf model file...")
        gguf_layout.addWidget(self.gguf_path_input)

        browse_gguf_btn = QPushButton("Browse GGUF...")
        browse_gguf_btn.clicked.connect(self.browse_gguf_model)
        gguf_layout.addWidget(browse_gguf_btn)
        model_layout.addLayout(gguf_layout)

        # llama-server.exe Path
        exe_layout = QHBoxLayout()
        exe_layout.addWidget(QLabel("Server EXE:"))
        saved_exe = self.config.get("llama_exe_path", "")
        default_exe = saved_exe if (saved_exe and os.path.exists(saved_exe)) else find_llama_server_exe()
        self.exe_path_input = QLineEdit(default_exe)
        self.exe_path_input.setPlaceholderText("Path to llama-server.exe...")
        exe_layout.addWidget(self.exe_path_input)

        browse_exe_btn = QPushButton("Browse EXE...")
        browse_exe_btn.clicked.connect(self.browse_llama_exe)
        exe_layout.addWidget(browse_exe_btn)
        model_layout.addLayout(exe_layout)

        # Server controls
        srv_ctrl_layout = QHBoxLayout()
        srv_ctrl_layout.addWidget(QLabel("URL:"))
        self.llama_url = QLineEdit(
            self.config.get("llama_url") or os.getenv("LLAMA_SERVER_URL", "http://127.0.0.1:8080")
        )
        self.llama_url.setFixedWidth(150)
        srv_ctrl_layout.addWidget(self.llama_url)

        srv_ctrl_layout.addWidget(QLabel("GPU (ngl):"))
        self.ngl_input = QSpinBox()
        self.ngl_input.setRange(0, 999)
        self.ngl_input.setValue(self.config.get("gpu_layers", 99))
        self.ngl_input.setFixedWidth(60)
        srv_ctrl_layout.addWidget(self.ngl_input)

        srv_ctrl_layout.addWidget(QLabel("Context:"))
        self.ctx_input = QSpinBox()
        self.ctx_input.setRange(2048, 131072)
        self.ctx_input.setSingleStep(2048)
        self.ctx_input.setValue(self.config.get("context_size", 16384))
        self.ctx_input.setFixedWidth(80)
        srv_ctrl_layout.addWidget(self.ctx_input)

        self.server_status_lbl = QLabel("🔴 Offline")
        self.server_status_lbl.setStyleSheet("font-weight: bold; color: #d9534f; margin-left: 6px;")
        srv_ctrl_layout.addWidget(self.server_status_lbl)

        srv_ctrl_layout.addStretch()

        self.start_server_btn = QPushButton("Start Server")
        self.start_server_btn.setStyleSheet("font-weight: bold; background-color: #2e7d32; color: white; padding: 3px 8px;")
        self.start_server_btn.clicked.connect(self.start_local_server)
        srv_ctrl_layout.addWidget(self.start_server_btn)

        self.stop_server_btn = QPushButton("Stop")
        self.stop_server_btn.clicked.connect(self.stop_local_server)
        srv_ctrl_layout.addWidget(self.stop_server_btn)

        model_layout.addLayout(srv_ctrl_layout)
        left_layout.addWidget(model_group)

        # Topic & URLs
        left_layout.addWidget(QLabel("<b>Topic Objective:</b>"))
        self.topic = QLineEdit(self.config.get("last_topic", ""))
        self.topic.setPlaceholderText("e.g. Disney D23 2026 Showcase Announcements & Reveals")
        left_layout.addWidget(self.topic)

        left_layout.addWidget(QLabel("<b>Research Source URLs (Articles, YouTube Videos — one per line):</b>"))
        self.urls = QPlainTextEdit()
        self.urls.setPlaceholderText("https://screenrant.com/...\nhttps://youtube.com/watch?v=...")
        self.urls.setMaximumHeight(85)
        left_layout.addWidget(self.urls)

        # Settings Form: Research Mode & 200 Words/Min Duration Selector
        form = QFormLayout()

        self.research_mode = QComboBox()
        self.research_mode.addItem("Free web research (recommended)", "free")
        self.research_mode.addItem("Supplied sources only", "sources")
        self.research_mode.addItem("Tavily enhanced", "tavily")

        saved_mode = self.config.get("research_mode", "free")
        for i in range(self.research_mode.count()):
            if self.research_mode.itemData(i) == saved_mode:
                self.research_mode.setCurrentIndex(i)
                break
        form.addRow("Research Mode:", self.research_mode)

        # Duration Selector (~200 words / minute benchmark: 5 min = 1000 words)
        dur_layout = QHBoxLayout()
        self.duration_combo = QComboBox()
        self.duration_combo.addItem("1 Minute (~200 words — Short / Reel)", (1, 200))
        self.duration_combo.addItem("3 Minutes (~600 words — Quick Video)", (3, 600))
        self.duration_combo.addItem("5 Minutes (~1,000 words — Standard YouTube)", (5, 1000))
        self.duration_combo.addItem("8 Minutes (~1,600 words — Mid-Length Monetized)", (8, 1600))
        self.duration_combo.addItem("10 Minutes (~2,000 words — Deep Dive)", (10, 2000))
        self.duration_combo.addItem("15 Minutes (~3,000 words — Documentary)", (15, 3000))
        self.duration_combo.addItem("20 Minutes (~4,000 words — Extended Special)", (20, 4000))
        self.duration_combo.addItem("Custom Duration...", "custom")

        self.custom_mins_input = QSpinBox()
        self.custom_mins_input.setRange(1, 60)
        self.custom_mins_input.setValue(self.config.get("target_minutes", 5))
        self.custom_mins_input.setSuffix(" mins")
        self.custom_mins_input.setFixedWidth(85)
        self.custom_mins_input.hide()

        self.custom_words_lbl = QLabel("(~1,000 words)")
        self.custom_words_lbl.setStyleSheet("color: #666; font-weight: bold;")
        self.custom_words_lbl.hide()

        self.custom_mins_input.valueChanged.connect(self.on_custom_minutes_changed)
        self.duration_combo.currentIndexChanged.connect(self.on_duration_combo_changed)

        saved_mins = self.config.get("target_minutes", 5)
        matched = False
        for i in range(self.duration_combo.count()):
            data = self.duration_combo.itemData(i)
            if isinstance(data, tuple) and data[0] == saved_mins:
                self.duration_combo.setCurrentIndex(i)
                matched = True
                break
        if not matched:
            self.duration_combo.setCurrentIndex(self.duration_combo.count() - 1)
            self.custom_mins_input.setValue(saved_mins)
            self.custom_mins_input.show()
            self.custom_words_lbl.show()

        dur_layout.addWidget(self.duration_combo)
        dur_layout.addWidget(self.custom_mins_input)
        dur_layout.addWidget(self.custom_words_lbl)
        dur_layout.addStretch()

        form.addRow("Video Length:", dur_layout)

        self.tavily = QLineEdit(self.config.get("tavily_key") or os.getenv("TAVILY_API_KEY", ""))
        self.tavily.setEchoMode(QLineEdit.Password)
        form.addRow("Tavily API Key (opt):", self.tavily)

        left_layout.addLayout(form)

        # Action Buttons
        actions = QHBoxLayout()
        self.generate_btn = QPushButton("🚀 RESEARCH + GENERATE")
        self.generate_btn.setStyleSheet(
            "QPushButton { font-weight: bold; background-color: #1976d2; color: white; padding: 8px 16px; font-size: 13px; }"
            "QPushButton:hover { background-color: #1565c0; }"
        )
        self.generate_btn.clicked.connect(self.on_click_generate)
        actions.addWidget(self.generate_btn)

        save_btn = QPushButton("Save Project")
        save_btn.clicked.connect(self.save_project)
        actions.addWidget(save_btn)

        export_btn = QPushButton("📁 Export Scripts...")
        export_btn.setStyleSheet("font-weight: bold;")
        export_btn.clicked.connect(self.export_scripts)
        actions.addWidget(export_btn)

        left_layout.addLayout(actions)

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 0)
        self.progress_bar.hide()
        left_layout.addWidget(self.progress_bar)

        self.status = QLabel("Ready.")
        left_layout.addWidget(self.status)

        # Real-Time Embedded Console Logs in Main Left Pane
        log_header = QHBoxLayout()
        log_header.addWidget(QLabel("<b>Real-Time Pipeline & Server Console:</b>"))
        log_header.addStretch()
        clear_log_btn = QPushButton("Clear Console")
        clear_log_btn.clicked.connect(self.clear_logs)
        log_header.addWidget(clear_log_btn)
        left_layout.addLayout(log_header)

        self.log_view = QPlainTextEdit()
        self.log_view.setReadOnly(True)
        self.log_view.setStyleSheet(
            "QPlainTextEdit { background-color: #161616; color: #dcdcdc; font-family: 'Consolas', 'Courier New', monospace; font-size: 12px; border-radius: 4px; }"
        )
        left_layout.addWidget(self.log_view)

        # ----------------------------------------------------
        # RIGHT PANE: Live Script Generation & Output Studio Tabs
        # ----------------------------------------------------
        self.right_widget = QWidget()
        right_layout = QVBoxLayout(self.right_widget)
        right_layout.setContentsMargins(10, 10, 10, 10)

        right_header = QHBoxLayout()
        right_header.addWidget(QLabel("<h3 style='margin:0;'>Script Studio & Live Generation</h3>"))
        right_header.addStretch()

        # Chatbot Assistant Button
        self.chat_btn = QPushButton("💬 Chat with AI (Assistant)")
        self.chat_btn.setStyleSheet(
            "QPushButton { font-weight: bold; background-color: #7b1fa2; color: white; padding: 4px 10px; }"
            "QPushButton:hover { background-color: #6a1b9a; }"
        )
        self.chat_btn.clicked.connect(self.open_ai_chat)
        right_header.addWidget(self.chat_btn)

        copy_btn = QPushButton("Copy Active Script")
        copy_btn.clicked.connect(self.copy_active_tab)
        right_header.addWidget(copy_btn)

        right_layout.addLayout(right_header)

        # Real-Time Word & Reading Time Status Bar in Studio Pane
        self.stats_bar = QWidget()
        self.stats_bar.setStyleSheet(
            "QWidget { background-color: #1e1e1e; border: 1px solid #333; border-radius: 6px; padding: 3px 8px; }"
        )
        stats_layout = QHBoxLayout(self.stats_bar)
        stats_layout.setContentsMargins(8, 4, 8, 4)

        self.word_count_lbl = QLabel("📊 <b>YouTube Script:</b> 0 words | <b>Est. Duration:</b> ~0.0 mins (@ 200 wpm) | <b>Characters:</b> 0")
        self.word_count_lbl.setStyleSheet("font-size: 12px; color: #64b5f6;")
        stats_layout.addWidget(self.word_count_lbl)
        stats_layout.addStretch()
        right_layout.addWidget(self.stats_bar)

        self.tabs = QTabWidget()

        self.script_b = QPlainTextEdit()
        self.script_b.setReadOnly(False)  # Editable for live writer tweaks
        self.script_b.setStyleSheet("font-size: 13px; line-height: 1.4;")
        self.tabs.addTab(self.script_b, "🎬 Version B — YouTube")

        self.script_a = QPlainTextEdit()
        self.script_a.setReadOnly(False)  # Editable
        self.script_a.setStyleSheet("font-size: 13px; line-height: 1.4;")
        self.tabs.addTab(self.script_a, "📽️ Version A — Documentary")

        self.research_view = QPlainTextEdit()
        self.research_view.setReadOnly(True)
        self.research_view.setStyleSheet("font-size: 12px; font-family: 'Consolas', monospace;")
        self.tabs.addTab(self.research_view, "📋 Research Brief")

        self.sources_view = QPlainTextEdit()
        self.sources_view.setReadOnly(True)
        self.sources_view.setStyleSheet("font-size: 12px;")
        self.tabs.addTab(self.sources_view, "🔗 Sources & Evidence")

        right_layout.addWidget(self.tabs)

        # Connect real-time word counter signals
        self.script_b.textChanged.connect(self.update_word_counts)
        self.script_a.textChanged.connect(self.update_word_counts)
        self.research_view.textChanged.connect(self.update_word_counts)
        self.sources_view.textChanged.connect(self.update_word_counts)
        self.tabs.currentChanged.connect(self.update_word_counts)

        self.splitter.addWidget(left_widget)
        self.splitter.addWidget(self.right_widget)
        self.splitter.setSizes([540, 840])

        self.setCentralWidget(self.splitter)

        # Non-blocking health monitor timer
        self.timer = QTimer(self)
        self.timer.setInterval(4000)
        self.timer.timeout.connect(self.check_server_health)
        self.timer.start()
        self.check_server_health()

    def update_word_counts(self):
        def count_words(text):
            if not text:
                return 0
            return len(re.findall(r'\b\w+\b', text))

        text_b = self.script_b.toPlainText()
        text_a = self.script_a.toPlainText()
        text_r = self.research_view.toPlainText()
        text_s = self.sources_view.toPlainText()

        words_b = count_words(text_b)
        words_a = count_words(text_a)
        words_r = count_words(text_r)
        words_s = count_words(text_s)

        # Update Tab Title Badges
        self.tabs.setTabText(0, f"🎬 Version B — YouTube ({words_b:,}w)" if words_b > 0 else "🎬 Version B — YouTube")
        self.tabs.setTabText(1, f"📽️ Version A — Documentary ({words_a:,}w)" if words_a > 0 else "📽️ Version A — Documentary")
        self.tabs.setTabText(2, f"📋 Research Brief ({words_r:,}w)" if words_r > 0 else "📋 Research Brief")
        self.tabs.setTabText(3, f"🔗 Sources & Evidence ({words_s:,}w)" if words_s > 0 else "🔗 Sources & Evidence")

        # Update Header Counter Banner
        current_idx = self.tabs.currentIndex()
        if current_idx == 0:
            mins = round(words_b / 200, 1)
            self.word_count_lbl.setText(
                f"📊 <b>YouTube Script:</b> <span style='color:#fff;'><b>{words_b:,}</b> words</span> &nbsp;|&nbsp; "
                f"<b>Est. Read Time:</b> <span style='color:#81c784;'>~{mins} mins</span> (@ 200 wpm) &nbsp;|&nbsp; "
                f"<b>Characters:</b> {len(text_b):,}"
            )
        elif current_idx == 1:
            mins = round(words_a / 200, 1)
            self.word_count_lbl.setText(
                f"📊 <b>Documentary Script:</b> <span style='color:#fff;'><b>{words_a:,}</b> words</span> &nbsp;|&nbsp; "
                f"<b>Est. Read Time:</b> <span style='color:#81c784;'>~{mins} mins</span> (@ 200 wpm) &nbsp;|&nbsp; "
                f"<b>Characters:</b> {len(text_a):,}"
            )
        elif current_idx == 2:
            self.word_count_lbl.setText(
                f"📊 <b>Research Brief:</b> <span style='color:#fff;'><b>{words_r:,}</b> words</span> &nbsp;|&nbsp; "
                f"<b>Characters:</b> {len(text_r):,}"
            )
        else:
            self.word_count_lbl.setText(
                f"📊 <b>Sources & Evidence:</b> <span style='color:#fff;'><b>{words_s:,}</b> words</span> &nbsp;|&nbsp; "
                f"<b>Characters:</b> {len(text_s):,}"
            )

    def on_duration_combo_changed(self):
        data = self.duration_combo.currentData()
        if data == "custom":
            self.custom_mins_input.show()
            self.custom_words_lbl.show()
            self.on_custom_minutes_changed()
        else:
            self.custom_mins_input.hide()
            self.custom_words_lbl.hide()

    def on_custom_minutes_changed(self):
        mins = self.custom_mins_input.value()
        approx_words = int(mins * 200)
        self.custom_words_lbl.setText(f"(~{approx_words} words)")

    def get_target_duration_and_words(self):
        data = self.duration_combo.currentData()
        if isinstance(data, tuple):
            return data[0], data[1]
        mins = self.custom_mins_input.value()
        words = int(mins * 200)
        return mins, words

    def copy_active_tab(self):
        current = self.tabs.currentWidget()
        if isinstance(current, QPlainTextEdit):
            text = current.toPlainText()
            if text:
                QApplication.clipboard().setText(text)
                self.status.setText("Copied active script to clipboard!")
            else:
                self.status.setText("Nothing to copy in active tab.")

    def open_ai_chat(self):
        current_tab_idx = self.tabs.currentIndex()
        tab_titles = ["Version B — YouTube", "Version A — Documentary", "Research Brief", "Sources & Evidence"]
        title = tab_titles[current_tab_idx] if current_tab_idx < len(tab_titles) else "Script"

        current_widget = self.tabs.currentWidget()
        active_text = current_widget.toPlainText() if isinstance(current_widget, QPlainTextEdit) else ""

        def apply_text_to_tab(new_text):
            if isinstance(current_widget, QPlainTextEdit):
                current_widget.setPlainText(new_text)

        dialog = AIChatDialog(
            parent=self,
            llama_url=self.llama_url.text().strip(),
            topic=self.topic.text().strip() or "Untitled",
            active_tab_title=title,
            active_text=active_text,
            brief_data=self.result.get("brief", {}) if self.result else {},
            apply_callback=apply_text_to_tab,
        )
        dialog.exec()

    def clear_logs(self):
        self.log_view.clear()

    def append_log(self, text: str):
        self.log_view.appendPlainText(text)
        self.log_view.moveCursor(QTextCursor.End)
        self.log_view.ensureCursorVisible()

    def on_research_progress(self, msg: str):
        self.status.setText(msg)
        now = datetime.now().strftime("%H:%M:%S")
        self.append_log(f"[{now}] {msg}")

    def on_stream_token(self, section: str, token: str):
        if section in self.token_buffer:
            self.token_buffer[section].append(token)

    def flush_stream_buffer(self):
        for section, tokens in self.token_buffer.items():
            if not tokens:
                continue
            chunk = "".join(tokens)
            tokens.clear()
            if section == "brief":
                self.research_view.moveCursor(QTextCursor.End)
                self.research_view.insertPlainText(chunk)
                self.research_view.ensureCursorVisible()
            elif section == "script_a":
                self.script_a.moveCursor(QTextCursor.End)
                self.script_a.insertPlainText(chunk)
                self.script_a.ensureCursorVisible()
            elif section == "script_b":
                self.script_b.moveCursor(QTextCursor.End)
                self.script_b.insertPlainText(chunk)
                self.script_b.ensureCursorVisible()

    def browse_gguf_model(self):
        current = self.gguf_path_input.text().strip()
        dir_hint = os.path.dirname(current) if current and os.path.exists(current) else str(get_app_dir())
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Select Local GGUF Model File",
            dir_hint,
            "GGUF Models (*.gguf);;All Files (*.*)",
        )
        if path:
            self.gguf_path_input.setText(path)
            self.save_current_config()

    def browse_llama_exe(self):
        current = self.exe_path_input.text().strip()
        dir_hint = os.path.dirname(current) if current and os.path.exists(current) else str(get_app_dir())
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Select llama-server.exe Binary",
            dir_hint,
            "Executable Files (*.exe);;All Files (*.*)",
        )
        if path:
            self.exe_path_input.setText(path)
            self.save_current_config()

    def save_current_config(self):
        mins, words = self.get_target_duration_and_words()
        data = {
            "gguf_model_path": self.gguf_path_input.text().strip(),
            "llama_exe_path": self.exe_path_input.text().strip(),
            "llama_url": self.llama_url.text().strip(),
            "gpu_layers": self.ngl_input.value(),
            "context_size": self.ctx_input.value(),
            "target_minutes": mins,
            "target_words": words,
            "research_mode": self.research_mode.currentData(),
            "tavily_key": self.tavily.text().strip(),
            "last_topic": self.topic.text().strip(),
        }
        save_config(data)

    def check_server_health(self):
        if self.worker and self.worker.isRunning():
            self.server_status_lbl.setText("🟢 Generating...")
            self.server_status_lbl.setStyleSheet("font-weight: bold; color: #5cb85c; margin-left: 6px;")
            return

        url = self.llama_url.text().strip()
        llama = LlamaServer(url)
        if llama.health(timeout=0.6):
            self.server_status_lbl.setText(f"🟢 Online")
            self.server_status_lbl.setStyleSheet("font-weight: bold; color: #5cb85c; margin-left: 6px;")
        else:
            if self.wait_thread and self.wait_thread.isRunning():
                self.server_status_lbl.setText("🟡 Loading...")
                self.server_status_lbl.setStyleSheet("font-weight: bold; color: #f0ad4e; margin-left: 6px;")
            else:
                self.server_status_lbl.setText("🔴 Offline")
                self.server_status_lbl.setStyleSheet("font-weight: bold; color: #d9534f; margin-left: 6px;")

    def start_local_server(self):
        self.save_current_config()
        exe = self.exe_path_input.text().strip()
        gguf = self.gguf_path_input.text().strip()

        if not os.path.isfile(exe):
            QMessageBox.warning(self, "Invalid llama-server EXE", f"llama-server.exe not found at:\n{exe}\n\nPlease click 'Browse EXE...' to select it.")
            return

        if not os.path.isfile(gguf):
            QMessageBox.warning(self, "Invalid GGUF Model", f"GGUF model file not found at:\n{gguf}\n\nPlease click 'Browse GGUF...' to select a valid .gguf model file.")
            return

        if self.server_proc_ref[0]:
            self.append_log("[ScriptMaker] Stopping existing server process...")
            self.server_proc_ref[0].stop()
            self.server_proc_ref[0] = None

        now = datetime.now().strftime("%H:%M:%S")
        self.append_log(f"\n[{now}] [ScriptMaker] Launching local llama-server...")
        self.append_log(f"[{now}] [ScriptMaker] Binary: {exe}")
        self.append_log(f"[{now}] [ScriptMaker] Model:  {gguf}")
        self.append_log(f"[{now}] [ScriptMaker] GPU offload layers: {self.ngl_input.value()} | Context: {self.ctx_input.value()}")
        self.append_log("-" * 65)

        try:
            self.status.setText("Starting local LLM server (loading model into memory)...")
            self.server_status_lbl.setText("🟡 Loading...")
            self.server_status_lbl.setStyleSheet("font-weight: bold; color: #f0ad4e; margin-left: 6px;")
            
            proc = LlamaServerProcess(
                exe_path=exe,
                model_path=gguf,
                port=8080,
                ngl=self.ngl_input.value(),
                context=self.ctx_input.value(),
                parallel=1,
                flash_attention=True,
                log_callback=self.log_bridge.log_message.emit,
            )
            proc.start()
            self.server_proc_ref[0] = proc

            self.wait_thread = ServerWaitThread(self.llama_url.text().strip(), timeout_sec=90)
            self.wait_thread.progress.connect(self.status.setText)
            self.wait_thread.ready.connect(self.on_server_startup_result)
            self.wait_thread.start()

        except Exception as exc:
            self.append_log(f"[ScriptMaker ERROR] {exc}")
            QMessageBox.critical(self, "Error Starting Server", str(exc))

    def on_server_startup_result(self, is_ready: bool):
        now = datetime.now().strftime("%H:%M:%S")
        if is_ready:
            self.status.setText("Local AI server is online and ready.")
            self.append_log(f"\n[{now}] [ScriptMaker SUCCESS] Local AI Server is ONLINE and ready at {self.llama_url.text().strip()}!\n")
            self.check_server_health()
        else:
            self.status.setText("Server failed to become ready in time.")
            self.append_log(f"\n[{now}] [ScriptMaker WARNING] Server did not report ready within 90 seconds. Check console logs above.\n")
            self.check_server_health()

    def stop_local_server(self):
        if self.server_proc_ref[0]:
            self.server_proc_ref[0].stop()
            self.server_proc_ref[0] = None
            now = datetime.now().strftime("%H:%M:%S")
            self.append_log(f"[{now}] [ScriptMaker] Local server stopped.")
            self.status.setText("Local server stopped.")
            self.check_server_health()
        else:
            QMessageBox.information(self, "Info", "No server process managed by ScriptMaker is currently running.")

    def on_click_generate(self):
        topic = self.topic.text().strip()
        urls = normalize_urls(self.urls.toPlainText())
        mode = self.research_mode.currentData()
        target_mins, target_words = self.get_target_duration_and_words()

        if not topic:
            QMessageBox.warning(self, "Missing topic", "Please enter a topic.")
            return

        if not urls:
            QMessageBox.warning(
                self,
                "Missing URLs",
                "Please add at least one source URL.",
            )
            return

        if mode == "tavily" and not self.tavily.text().strip():
            QMessageBox.warning(
                self,
                "Tavily key required",
                "Tavily mode needs an API key. Use Free web research instead if you want no API key.",
            )
            return

        # Pre-generation options dialog
        opt_dialog = GenerateOptionsDialog(self, target_mins, target_words)
        if opt_dialog.exec() != QDialog.Accepted:
            return

        do_brief = opt_dialog.chk_brief.isChecked()
        do_yt = opt_dialog.chk_yt.isChecked()
        do_doc = opt_dialog.chk_doc.isChecked()
        check_scope = opt_dialog.chk_scope_alert.isChecked()

        if not do_brief and not do_yt and not do_doc:
            QMessageBox.warning(self, "Nothing Selected", "Please select at least one component to generate.")
            return

        self.start_generation(do_brief, do_yt, do_doc, check_scope, target_words, target_mins)

    def start_generation(self, do_brief, do_yt, do_doc, check_scope, target_words, target_mins):
        self.save_current_config()

        topic = self.topic.text().strip()
        urls = normalize_urls(self.urls.toPlainText())
        mode = self.research_mode.currentData()

        # Clear active stream buffers
        self.token_buffer = {"brief": [], "script_a": [], "script_b": []}
        if do_brief:
            self.research_view.clear()
            self.sources_view.clear()
        if do_doc:
            self.script_a.clear()
        if do_yt:
            self.script_b.clear()

        # Focus script studio
        self.splitter.setSizes([500, 880])
        if do_yt:
            self.tabs.setCurrentIndex(0)
        elif do_doc:
            self.tabs.setCurrentIndex(1)
        else:
            self.tabs.setCurrentIndex(2)

        self.generate_btn.setEnabled(False)
        self.progress_bar.show()

        now = datetime.now().strftime("%H:%M:%S")
        self.append_log(f"\n[{now}] [ScriptMaker] ===== STARTING PIPELINE =====")
        self.append_log(f"[{now}] [ScriptMaker] Topic: {topic}")
        self.append_log(f"[{now}] [ScriptMaker] Target Duration: {target_mins} mins (~{target_words} words)")
        self.append_log(f"[{now}] [ScriptMaker] Components: Brief={do_brief} | YouTube={do_yt} | Documentary={do_doc}")
        self.append_log(f"[{now}] [ScriptMaker] Sources count: {len(urls)}")

        self.worker = Worker(
            urls=urls,
            topic=topic,
            mode=mode,
            tavily_key=self.tavily.text().strip(),
            llama_url=self.llama_url.text().strip(),
            llama_exe=self.exe_path_input.text().strip(),
            gguf_model=self.gguf_path_input.text().strip(),
            ngl=self.ngl_input.value(),
            context=self.ctx_input.value(),
            target_words=target_words,
            target_minutes=target_mins,
            do_brief=do_brief,
            do_youtube=do_yt,
            do_doc=do_doc,
            check_scope=check_scope,
            server_proc_ref=self.server_proc_ref,
            log_callback=self.log_bridge.log_message.emit,
        )
        self.worker.progress.connect(self.on_research_progress)
        self.worker.stream_token.connect(self.on_stream_token)
        self.worker.finished_ok.connect(self.on_done)
        self.worker.failed.connect(self.on_error)
        self.worker.start()

    def on_done(self, result):
        self.result = result
        self.flush_stream_buffer()
        self.progress_bar.hide()
        self.generate_btn.setEnabled(True)
        self.status.setText("Completed.")
        self.check_server_health()

        brief = result.get("brief", {})
        if brief:
            self.research_view.setPlainText(
                json.dumps(brief, indent=2, ensure_ascii=False)
            )

        if result.get("script_a"):
            self.script_a.setPlainText(result["script_a"])
        if result.get("script_b"):
            self.script_b.setPlainText(result["script_b"])

        sources_text = []
        for source in brief.get("sources", []):
            sources_text.append(
                f"{source.get('title')}\n"
                f"{source.get('url')}\n"
                f"Status: {'OK' if source.get('fetched_ok') else 'FAILED'}\n"
                f"Error: {source.get('error') or ''}\n"
            )

        for result_item in result.get("web_results", []):
            sources_text.append(
                f"[SEARCH] {result_item.get('title')}\n"
                f"{result_item.get('url')}\n"
            )

        if sources_text:
            self.sources_view.setPlainText("\n---\n".join(sources_text))
        
        self.update_word_counts()

        now = datetime.now().strftime("%H:%M:%S")
        self.append_log(f"[{now}] [ScriptMaker SUCCESS] Generation tasks finished successfully!")
        
        if result.get("script_b"):
            self.tabs.setCurrentIndex(0)
        elif result.get("script_a"):
            self.tabs.setCurrentIndex(1)
        else:
            self.tabs.setCurrentIndex(2)

    def on_error(self, message):
        self.flush_stream_buffer()
        self.progress_bar.hide()
        self.generate_btn.setEnabled(True)
        self.status.setText("Failed.")
        self.check_server_health()
        now = datetime.now().strftime("%H:%M:%S")
        self.append_log(f"[{now}] [ScriptMaker ERROR] {message}")
        QMessageBox.critical(self, "Generation error", message)

    def save_project(self):
        if not self.result:
            QMessageBox.information(
                self,
                "Nothing to save",
                "Generate a project first.",
            )
            return

        path, _ = QFileDialog.getSaveFileName(
            self,
            "Save project",
            "script_project.json",
            "JSON Files (*.json)",
        )

        if not path:
            return

        mins, words = self.get_target_duration_and_words()
        payload = {
            "topic": self.topic.text().strip(),
            "source_urls": normalize_urls(self.urls.toPlainText()),
            "research_mode": self.research_mode.currentData(),
            "target_minutes": mins,
            "target_words": words,
            **self.result,
        }

        Path(path).write_text(
            json.dumps(payload, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        self.status.setText(f"Saved: {path}")

    def export_scripts(self):
        if not self.result:
            QMessageBox.information(
                self,
                "Nothing to export",
                "Please generate scripts first before exporting.",
            )
            return

        mins, words = self.get_target_duration_and_words()
        dur_str = f"{mins} mins (~{words} words)"

        dialog = ExportDialog(self, self.topic.text().strip(), self.result, dur_str)
        if dialog.exec() == QDialog.Accepted and dialog.exported_folder:
            folder = dialog.exported_folder
            file_list_str = "\n".join([f"• {name}" for name in dialog.exported_files])

            self.status.setText(f"Exported to: {folder}")
            now = datetime.now().strftime("%H:%M:%S")
            self.append_log(f"[{now}] [ScriptMaker] Exported {len(dialog.exported_files)} files to {folder}")

            msg_box = QMessageBox(self)
            msg_box.setWindowTitle("Export Successful")
            msg_box.setIcon(QMessageBox.Information)
            msg_box.setText(
                f"Successfully exported {len(dialog.exported_files)} file(s) to:\n{folder}\n\n"
                f"{file_list_str}"
            )
            open_folder_btn = msg_box.addButton("Open Folder", QMessageBox.ActionRole)
            msg_box.addButton(QMessageBox.Ok)
            msg_box.exec()

            if msg_box.clickedButton() == open_folder_btn:
                try:
                    os.startfile(str(folder))
                except Exception:
                    pass

    def closeEvent(self, event):
        self.save_current_config()
        if self.server_proc_ref[0]:
            self.server_proc_ref[0].stop()
            self.server_proc_ref[0] = None
        event.accept()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    icon_path = get_icon_path()
    if icon_path:
        app.setWindowIcon(QIcon(icon_path))
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
